CREATE DATABASE IF NOT EXISTS parasja_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE parasja_app;

CREATE TABLE IF NOT EXISTS parasjot (
    id INT AUTO_INCREMENT PRIMARY KEY,
    volgorde INT NOT NULL,
    naam_hebreeuws VARCHAR(100) NOT NULL,
    naam_nl VARCHAR(100) NOT NULL,
    naam_transliteratie VARCHAR(100) NOT NULL,
    boek ENUM('Bereshit','Shemot','Vayikra','Bamidbar','Devarim') NOT NULL,
    verzen_van VARCHAR(50),
    verzen_tot VARCHAR(50),
    samenvatting TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parasja_schema (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parasja_id INT NOT NULL,
    shabbat_datum DATE NOT NULL,
    joods_jaar INT NOT NULL,
    gecombineerd_met INT DEFAULT NULL,
    FOREIGN KEY (parasja_id) REFERENCES parasjot(id),
    UNIQUE KEY unique_datum (shabbat_datum)
);

CREATE TABLE IF NOT EXISTS notities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parasja_id INT NOT NULL,
    parasja_schema_id INT DEFAULT NULL,
    titel VARCHAR(255),
    tekst TEXT NOT NULL,
    aangemaakt_op TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    bijgewerkt_op TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (parasja_id) REFERENCES parasjot(id)
);

CREATE TABLE IF NOT EXISTS foto_notities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parasja_id INT NOT NULL,
    parasja_schema_id INT DEFAULT NULL,
    bestandsnaam VARCHAR(255) NOT NULL,
    origineel_naam VARCHAR(255),
    ocr_tekst TEXT,
    ocr_bewerkt TEXT,
    notitie VARCHAR(255),
    aangemaakt_op TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parasja_id) REFERENCES parasjot(id)
);

-- 54 Parasjot
INSERT INTO parasjot (volgorde, naam_hebreeuws, naam_nl, naam_transliteratie, boek, verzen_van, verzen_tot, samenvatting) VALUES
(1,  'בְּרֵאשִׁית', 'In het begin', 'Bereshit',    'Bereshit', 'Gen 1:1',  'Gen 6:8',   'God schept de wereld in zes dagen. Adam en Eva leven in de hof van Eden, maar eten van de verboden vrucht en worden verbannen. Kaïn doodt zijn broer Abel. De generaties van Adam tot Noach worden beschreven.'),
(2,  'נֹחַ',        'Noach',        'Noach',        'Bereshit', 'Gen 6:9',  'Gen 11:32', 'God ziet de verdorvenheid van de mens en besluit een vloed te sturen. Noach bouwt een ark en redt zijn familie en de dieren. Na de vloed sluit God een verbond met Noach, gesymboliseerd door een regenboog. De toren van Babel wordt gebouwd en de talen worden verward.'),
(3,  'לֶךְ-לְךָ',   'Ga voor jezelf','Lech Lecha',  'Bereshit', 'Gen 12:1', 'Gen 17:27', 'God roept Avram op zijn land te verlaten en naar Kanaän te gaan. Avram en Sarai reizen naar Egypte. Het verbond tussen God en Avram wordt gesloten; zijn naam wordt veranderd in Abraham. De besnijdenis wordt als teken van het verbond ingesteld.'),
(4,  'וַיֵּרָא',    'En Hij verscheen','Vayeira',    'Bereshit', 'Gen 18:1', 'Gen 22:24', 'God verschijnt aan Abraham bij de eiken van Mamre. Drie engelen bezoeken Abraham en kondigen de geboorte van Isaak aan. Sodom en Gomorra worden vernietigd. Isaak wordt geboren. De binding van Isaak (Akeda) vindt plaats op de berg Moria.'),
(5,  'חַיֵּי שָׂרָה', 'Het leven van Sara', 'Chayei Sarah', 'Bereshit', 'Gen 23:1', 'Gen 25:18', "Sara overlijdt op 127-jarige leeftijd. Abraham koopt de grot van Machpela als begraafplaats. Abraham stuurt zijn dienaar Eliëzer om een vrouw te zoeken voor Isaak. Eliëzer vindt Rivka. Abraham hertrouwt met Ketura en overlijdt op 175-jarige leeftijd."),
(6,  'תּוֹלְדֹת',   'Generaties',   'Toldot',       'Bereshit', 'Gen 25:19','Gen 28:9',  'Isaak en Rivka krijgen de tweeling Esau en Jakob. Esau verkoopt zijn eerstgeboorterecht aan Jakob voor een kom linzensoep. Jakob ontvangt met list de zegen van zijn vader Isaak, bestemd voor Esau. Esau wil Jakob doden, en Jakob vlucht naar Charan.'),
(7,  'וַיֵּצֵא',    'En hij ging uit','Vayeitzei',   'Bereshit', 'Gen 28:10','Gen 32:3',  'Jakob droomt van een ladder naar de hemel. Jakob arriveert bij Laban en werkt veertien jaar voor zijn dochters Lea en Rachel. Jakob krijgt twaalf zonen en één dochter. Jakob vlucht met zijn gezin uit het huis van Laban terug naar Kanaän.'),
(8,  'וַיִּשְׁלַח',  'En hij stuurde','Vayishlach',  'Bereshit', 'Gen 32:4', 'Gen 36:43', "Jakob stuurt boodschappers naar Esau. 's Nachts worstelt Jakob met een engel en krijgt de naam Israël. Jakob en Esau verzoenen zich. Dina wordt onteerd door Sichem. Jakob keert terug naar Betel. Rachel sterft bij de geboorte van Benjamin."),
(9,  'וַיֵּשֶׁב',   'En hij woonde', 'Vayeishev',   'Bereshit', 'Gen 37:1', 'Gen 40:23', 'Jakob woont in Kanaän. Jozef, de geliefde zoon van Jakob, wordt door zijn broers gehaat vanwege zijn dromen en zijn veelkleurige mantel. Zijn broers gooien hem in een put en verkopen hem als slaaf naar Egypte. Het verhaal van Juda en Tamar. Jozef in Egypte.'),
(10, 'מִקֵּץ',      'Aan het einde', 'Mikeitz',     'Bereshit', 'Gen 41:1', 'Gen 44:17', 'Farao droomt van zeven vette en zeven magere koeien. Jozef legt de dromen uit en wordt aangesteld als onderkoning van Egypte. De broers van Jozef komen naar Egypte om graan te kopen. Jozef herkent zijn broers maar maakt zich nog niet bekend.'),
(11, 'וַיִּגַּשׁ',   'En hij naderde','Vayigash',    'Bereshit', 'Gen 44:18','Gen 47:27', 'Juda smeekt Jozef om Benjamin vrij te laten. Jozef onthult zich aan zijn broers. Farao nodigt het gezin van Jakob uit naar Egypte te komen. Jakob trekt met zijn hele gezin naar Egypte. Jozef regeert Egypte wijs tijdens de hongersnood.'),
(12, 'וַיְחִי',     'En hij leefde', 'Vayechi',     'Bereshit', 'Gen 47:28','Gen 50:26', 'Jakob leeft zeventien jaar in Egypte. Op zijn sterfbed zegent Jakob zijn zonen en kleinzonen. Jakob overlijdt en wordt teruggebracht naar Kanaän om begraven te worden in de grot van Machpela. Jozef troost zijn broers en overlijdt zelf op 110-jarige leeftijd.'),
(13, 'שְׁמוֹת',     'Namen',         'Shemot',      'Shemot',   'Ex 1:1',   'Ex 6:1',    'De Israëlieten worden slaven in Egypte. Mozes wordt geboren en door de dochter van Farao gered. Mozes vlucht naar Midian en ziet God in de brandende braamstruik. God stuurt Mozes terug naar Egypte om zijn volk te bevrijden. De eerste confrontatie met Farao.'),
(14, 'וָאֵרָא',     'En Ik verscheen','Vaera',       'Shemot',   'Ex 6:2',   'Ex 9:35',   'God herhaalt zijn belofte aan Mozes. De eerste zeven plagen treffen Egypte: bloed, kikkers, luizen, wilde dieren, veepest, zweren en hagel. Farao weigert steeds opnieuw het volk te laten gaan.'),
(15, 'בֹּא',        'Kom',            'Bo',          'Shemot',   'Ex 10:1',  'Ex 13:16',  'De achtste en negende plaag: sprinkhanen en duisternis. De tiende plaag wordt aangekondigd: de dood van de eerstgeborenen. Het Pesachfeest wordt ingesteld. De Israëlieten verlaten Egypte na 430 jaar slavernij.'),
(16, 'בְּשַׁלַּח',  'Toen hij liet gaan','Beshalach', 'Shemot',  'Ex 13:17', 'Ex 17:16',  "Farao achtervolgt de Israëlieten. God splijt de Rode Zee en de Israëlieten trekken er droogvoets doorheen. Farao's leger verdrinkt. Mozes en Mirjam zingen een lied. Het manna en de kwartels verschijnen in de woestijn. De strijd met Amalek."),
(17, 'יִתְרוֹ',     'Jitro',          'Yitro',       'Shemot',   'Ex 18:1',  'Ex 20:23',  'Jitro, de schoonvader van Mozes, bezoekt hem en adviseert een rechtssysteem op te zetten. Het volk Israël arriveert bij de berg Sinaï. De Tien Geboden worden door God gegeven te midden van donder en bliksem.'),
(18, 'מִשְׁפָּטִים', 'Wetten',        'Mishpatim',   'Shemot',   'Ex 21:1',  'Ex 24:18',  "Een reeks burgerlijke en religieuze wetten wordt gegeven, waaronder regels over slaven, geweld, eigendom, de drie pelgrimsfeesten en het verbod op het koken van een geitenbokje in de melk van zijn moeder. Het verbond wordt bezegeld met bloed. Mozes stijgt op naar de berg Sinaï."),
(19, 'תְּרוּמָה',   'Heffing/Bijdrage','Terumah',    'Shemot',   'Ex 25:1',  'Ex 27:19',  'God geeft gedetailleerde instructies voor de bouw van de Mishkan (Tabernakel): de Ark van het Verbond, de menora, de tafel voor het toonbrood en de andere heilige voorwerpen.'),
(20, 'תְּצַוֶּה',   'Jij zult gebieden','Tetzaveh',  'Shemot',   'Ex 27:20', 'Ex 30:10',  'Instructies voor de priesterlijke gewaden van Aäron en zijn zonen. De wijding van de priesters wordt beschreven. Het altaar van reukwerk wordt voorgeschreven.'),
(21, 'כִּי תִשָּׂא', 'Wanneer jij heft','Ki Tissa',   'Shemot',   'Ex 30:11', 'Ex 34:35',  'Het volk Israël maakt het Gouden Kalf terwijl Mozes op de berg is. God wil het volk vernietigen, maar Mozes pleit voor hen. Mozes verbreekt de stenen tafelen. God vergeeft het volk. Mozes ontvangt nieuwe tafelen en zijn gezicht gaat stralen.'),
(22, 'וַיַּקְהֵל',   'En hij verzamelde','Vayakhel',  'Shemot',   'Ex 35:1',  'Ex 38:20',  'Mozes roept het volk bijeen en herhaalt het bevel van de sabbat. Het volk brengt vrijwillige bijdragen voor de Tabernakel. Betsaleël en Oholiab leiden de constructie van de Mishkan en al zijn voorwerpen.'),
(23, 'פְקוּדֵי',    'Berekeningen',  'Pekudei',     'Shemot',   'Ex 38:21', 'Ex 40:38',  'Een overzicht van alle materialen die zijn gebruikt voor de Mishkan. De priestergewaden worden gemaakt. De Mishkan wordt opgericht op de eerste van Nisan. God vult de Mishkan met zijn aanwezigheid in een wolk.'),
(24, 'וַיִּקְרָא',   'En Hij riep',  'Vayikra',     'Vayikra',  'Lev 1:1',  'Lev 5:26',  'God roept Mozes uit de Mishkan en geeft instructies over de verschillende soorten offeranden: brandoffers, graanoffers, vredesoffers, zondoffers en schuldoffers.'),
(25, 'צַו',         'Gebied',        'Tzav',         'Vayikra',  'Lev 6:1',  'Lev 8:36',  'Aanvullende instructies voor de priesters over de offers. De wijding van Aäron en zijn zonen als priesters wordt beschreven, inclusief de zeven dagen van inwijding.'),
(26, 'שְּׁמִינִי',   'Achtste',       'Shemini',     'Vayikra',  'Lev 9:1',  'Lev 11:47', 'Op de achtste dag van de inwijding brengen Aäron en zijn zonen offers. Vuur daalt neer van God. De zonen van Aäron, Nadav en Avihu, brengen vreemd vuur en sterven. De spijswetten (kasjroet) worden uiteengezet.'),
(27, 'תַזְרִיעַ',   'Zij zal zwanger worden','Tazria','Vayikra', 'Lev 12:1', 'Lev 13:59', 'Reinigingsrituelen na de geboorte. Gedetailleerde wetten over tzaraat (huidziekte), de priester onderzoekt de persoon en de woning.'),
(28, 'מְּצֹרָע',    'De melaatse',   'Metzora',     'Vayikra',  'Lev 14:1', 'Lev 15:33', 'Het reinigingsproces voor iemand die hersteld is van tzaraat. De reiniging van een besmet huis. Wetten over lichamelijke onreinheid.'),
(29, 'אַחֲרֵי מוֹת', 'Na de dood',   'Acharei Mot', 'Vayikra',  'Lev 16:1', 'Lev 18:30', 'De dienst van de Hogepriester op Jom Kippoer wordt beschreven, inclusief de twee geiten. Verbod op bloed eten. Verboden seksuele relaties worden opgesomd.'),
(30, 'קְדשִׁים',    'Heiligen',      'Kedoshim',    'Vayikra',  'Lev 19:1', 'Lev 20:27', '"Wees heilig, want Ik, de Eeuwige jullie God, ben heilig." Een breed scala aan ethische en rituele wetten, waaronder de geboden om de naaste lief te hebben als jezelf.'),
(31, 'אֱמֹר',       'Spreek',        'Emor',        'Vayikra',  'Lev 21:1', 'Lev 24:23', 'Wetten voor de priesters over reinheid en lichamelijke gebreken. De heilige feestdagen van het jaar worden beschreven: Sjabbat, Pesach, Sjawoeot, Rosj Hasjana, Jom Kippoer, Soekot.'),
(32, 'בְּהַר',      'Op de berg',    'Behar',       'Vayikra',  'Lev 25:1', 'Lev 26:2',  'Op de berg Sinaï worden de wetten van het sjemita (sabbatsjaar) en het jubeljaar gegeven. Regels over de verkoop van land, vrijkoop van eigendom en vrijlating van slaven.'),
(33, 'בְּחֻקֹּתַי',  'In mijn wetten','Bechukotai',  'Vayikra',  'Lev 26:3', 'Lev 27:34', 'God belooft zegeningen als Israël zijn wetten volgt. Vervloekingen worden opgelijst als Israël afwijkt. Het boek Vayikra sluit af met wetten over geloften en tienden.'),
(34, 'בְּמִדְבַּר',  'In de woestijn','Bamidbar',    'Bamidbar', 'Num 1:1',  'Num 4:20',  'God beveelt een volkstelling van de mannelijke Israëlieten ouder dan twintig. De stam Levi wordt apart geteld en aangewezen voor de dienst in de Mishkan. De kamperingsvolgorde rondom de Mishkan wordt beschreven.'),
(35, 'נָשֹׂא',      'Neem op',       'Nasso',       'Bamidbar', 'Num 4:21', 'Num 7:89',  'De taken van de Levitische families worden beschreven. Wetten over priesterlijk rechtspreken, de sota-proef en het nazireeërsgelofte. De priesterlijke zegen (Birkat Kohanim). De offergaven van de stamhoofden bij de inwijding van de Mishkan.'),
(36, 'בְּהַעֲלֹתְךָ', 'Wanneer jij opheft','Beha\'alotecha','Bamidbar','Num 8:1','Num 12:16','De menora wordt aangestoken. De Levieten worden gewijd. Een tweede Pesach voor wie onrein was. De wolk en het vuur boven de Mishkan. De zilveren trompetten. De Israëlieten trekken weg van de Sinaï. Mozes klaagt over de last van het leiderschap. God stuurt kwartels. Mirjam en Aäron spreken kwaad over Mozes.'),
(37, 'שְׁלַח-לְךָ',  'Stuur voor jezelf','Shelach',  'Bamidbar', 'Num 13:1', 'Num 15:41', 'Twaalf verspieders worden gestuurd naar Kanaän. Tien van hen brengen een slechte boodschap en het volk rouwt. God straft de generatie van de woestijn: zij zullen veertig jaar zwerven. De wetten van de challah en de tzitzit.'),
(38, 'קֹרַח',       'Korach',        'Korach',      'Bamidbar', 'Num 16:1', 'Num 18:32', 'Korach en zijn aanhangers komen in opstand tegen Mozes en Aäron. De aarde opent zich en verslindt Korach. God bevestigt het priesterschap van Aäron door zijn staf die bloeit. Regels over de taken en vergoedingen van priesters en Levieten.'),
(39, 'חֻקַּת',      'Wet van',       'Chukat',      'Bamidbar', 'Num 19:1', 'Num 22:1',  'De wet van de rode koe voor reiniging van doodsverontreiniging. Mirjam sterft. Het volk klaagt over water; Mozes slaat op de rots en wordt gestraft door niet het beloofde land te mogen betreden. Aäron sterft op de berg Hor. De koperen slang.'),
(40, 'בָּלָק',       'Balak',         'Balak',       'Bamidbar', 'Num 22:2', 'Num 25:9',  "Balak, de koning van Moab, huurt de profeet Bileam in om Israël te vervloeken. Bileams ezelin spreekt. In plaats van te vervloeken, zegent Bileam Israël driemaal. Israël begaat ontucht met de Moabitische vrouwen en aanbidt Baäl Peor."),
(41, 'פִּינְחָס',    'Pinchas',       'Pinchas',     'Bamidbar', 'Num 25:10','Num 30:1',  'Pinchas ontvangt een verbond van vrede voor zijn daadkracht. Een nieuwe volkstelling. De dochters van Tselofchad vragen om een erfenis. Jozua wordt aangesteld als opvolger van Mozes. De dagelijkse en feestdagofers worden beschreven.'),
(42, 'מַּטּוֹת',     'Stammen',       'Matot',       'Bamidbar', 'Num 30:2', 'Num 32:42', 'Wetten over geloften. De oorlog tegen Midian. De stammen Ruben en Gad vragen om het land ten oosten van de Jordaan. Mozes stemt toe op voorwaarde dat zij meedoen aan de verovering van Kanaän.'),
(43, 'מַסְעֵי',     'De reizen',     'Masei',       'Bamidbar', 'Num 33:1', 'Num 36:13', "De 42 reizen van Israël door de woestijn worden opgesomd. Instructies voor de verovering en verdeling van Kanaän. Grenzen van het land. Vrijsteden voor onopzettelijke doodslag. De dochters van Tselofchad trouwen binnen hun stam. Het boek Bamidbar sluit af."),
(44, 'דְּבָרִים',   'Woorden',       'Devarim',     'Devarim',  'Deut 1:1', 'Deut 3:22', 'Mozes begint zijn afscheidsrede aan het volk Israël op de vlakten van Moab. Hij blikt terug op de veertig jaar in de woestijn: de spionnen, de omzwervingen, de overwinningen op Sichon en Og.'),
(45, 'וָאֶתְחַנַּן', 'En ik smeekte', 'Vaetchanan',  'Devarim',  'Deut 3:23','Deut 7:11', "Mozes smeekt God hem het land te laten betreden, maar God weigert. Mozes spoort het volk aan de Torah te gehoorzamen. De Tien Geboden worden herhaald. Het Sjema Jisraeel wordt uitgesproken. Het verbod op gemengde huwelijken."),
(46, 'עֵקֶב',       'Gevolg/Hiel',   'Eikev',       'Devarim',  'Deut 7:12','Deut 11:25','Mozes belooft zegeningen bij gehoorzaamheid. Hij herinnert het volk aan Gods voorzienigheid in de woestijn: het manna, de kleding die niet versleet. De tweede alinea van het Sjema. Het goede land Kanaän wordt beschreven.'),
(47, 'רְאֵה',       'Zie',           'Reeh',        'Devarim',  'Deut 11:26','Deut 16:17','Mozes stelt het volk voor een keuze: zegen of vloek. Wetten over de centrale aanbidding, valse profeten, spijswetten, tienden, het remisiejaar, de vrijlating van slaven, de drie pelgrimsfeesten.'),
(48, 'שֹׁפְטִים',   'Rechters',      'Shoftim',     'Devarim',  'Deut 16:18','Deut 21:9','Aanstelling van rechters en functionarissen. Wetten over een koning. De steden van de priesters en Levieten. De profeet die God zal sturen als opvolger van Mozes. Vluchtsteden. Oorlogswetten. De procedure voor een onopgeloste moord.'),
(49, 'כִּי-תֵצֵא',  'Wanneer jij uittrekt','Ki Teitzei','Devarim', 'Deut 21:10','Deut 25:19','Een uitgebreide verzameling wetten: vrouw gevangen in oorlog, erfrecht van de eerstgeborene, weerspannige zoon, begrafenis, verloren bezit, kruisen van soorten, regels voor huwelijk en scheiding, gewichten en maten, het uitwissen van Amalek.'),
(50, 'כִּי-תָבוֹא',  'Wanneer jij binnenkomt','Ki Tavo', 'Devarim', 'Deut 26:1','Deut 29:8','Bij aankomst in het land: de eerstelingen brengen, het gebed van dankbaarheid. De zegeningen en vervloekingen op de bergen Gerizim en Ebal. De Tochacha: een lange serie vervloekingen bij ontrouw aan God. Mozes herinnert het volk aan Gods wonderen.'),
(51, 'נִצָּבִים',    'Jullie staan',  'Nitzavim',    'Devarim',  'Deut 29:9','Deut 30:20','Mozes sluit het verbond met heel het volk, ook met hen die er nog niet zijn. De teshuvah (terugkeer): God zal het volk terug brengen. "De Torah is niet in de hemel." Het leven en de dood worden voor het volk gesteld; Mozes kiest voor het leven.'),
(52, 'וַיֵּלֶךְ',    'En hij ging',   'Vayelech',    'Devarim',  'Deut 31:1','Deut 31:30','Mozes is 120 jaar oud en kondigt aan dat hij niet meer kan leiden. Hij installeert Jozua als zijn opvolger. Mozes schrijft de Torah op en geeft die aan de priesters. Het gebod om de Torah elke zeven jaar voor te lezen tijdens het jubeljaar.'),
(53, 'הַאֲזִינוּ',   'Luister',       'Haazinu',     'Devarim',  'Deut 32:1','Deut 32:52','Het lied van Mozes (Haazinu): een poëtisch getuigenis over Israëls toekomst, Gods trouw en de gevolgen van afvalligheid. God vertelt Mozes dat hij op de berg Nebo zal sterven nadat hij het land heeft gezien.'),
(54, 'וְזֹאת הַבְּרָכָה','En dit is de zegen','Vezot Haberacha','Devarim','Deut 33:1','Deut 34:12','Mozes zegent elk van de twaalf stammen afzonderlijk. Mozes beklimmt de berg Nebo en ziet het beloofde land van verre. Mozes overlijdt op 120-jarige leeftijd. "En er is nooit meer een profeet opgestaan in Israël als Mozes, die God kende van aangezicht tot aangezicht."');

-- Parasja schema 5786 (2025-2026)
INSERT INTO parasja_schema (parasja_id, shabbat_datum, joods_jaar, gecombineerd_met) VALUES
(1,  '2025-10-25', 5786, NULL),
(2,  '2025-11-01', 5786, NULL),
(3,  '2025-11-08', 5786, NULL),
(4,  '2025-11-15', 5786, NULL),
(5,  '2025-11-22', 5786, NULL),
(6,  '2025-11-29', 5786, NULL),
(7,  '2025-12-06', 5786, NULL),
(8,  '2025-12-13', 5786, NULL),
(9,  '2025-12-20', 5786, NULL),
(10, '2025-12-27', 5786, NULL),
(11, '2026-01-03', 5786, NULL),
(12, '2026-01-10', 5786, NULL),
(13, '2026-01-17', 5786, NULL),
(14, '2026-01-24', 5786, NULL),
(15, '2026-01-31', 5786, NULL),
(16, '2026-02-07', 5786, NULL),
(17, '2026-02-14', 5786, NULL),
(18, '2026-02-21', 5786, NULL),
(19, '2026-02-28', 5786, NULL),
(20, '2026-03-07', 5786, NULL),
(21, '2026-03-14', 5786, NULL),
(22, '2026-03-21', 5786, 23),
(24, '2026-03-28', 5786, NULL),
(25, '2026-04-04', 5786, NULL),
(26, '2026-04-25', 5786, NULL),
(27, '2026-05-02', 5786, 28),
(29, '2026-05-09', 5786, 30),
(31, '2026-05-16', 5786, NULL),
(32, '2026-05-23', 5786, 33),
(34, '2026-05-30', 5786, NULL),
(35, '2026-06-13', 5786, NULL),
(36, '2026-06-20', 5786, NULL),
(37, '2026-06-27', 5786, NULL),
(38, '2026-07-04', 5786, NULL),
(39, '2026-07-11', 5786, NULL),
(40, '2026-07-18', 5786, NULL),
(41, '2026-07-25', 5786, NULL),
(42, '2026-08-01', 5786, 43),
(44, '2026-08-08', 5786, NULL),
(45, '2026-08-15', 5786, NULL),
(46, '2026-08-22', 5786, NULL),
(47, '2026-08-29', 5786, NULL),
(48, '2026-09-05', 5786, NULL),
(49, '2026-09-12', 5786, NULL),
(50, '2026-09-19', 5786, NULL),
(51, '2026-09-26', 5786, 52);

-- Parasja schema 5787 (2026-2027)
INSERT INTO parasja_schema (parasja_id, shabbat_datum, joods_jaar, gecombineerd_met) VALUES
(53, '2026-10-10', 5787, NULL),
(54, '2026-10-17', 5787, NULL),
(1,  '2026-10-24', 5787, NULL),
(2,  '2026-10-31', 5787, NULL),
(3,  '2026-11-07', 5787, NULL),
(4,  '2026-11-14', 5787, NULL),
(5,  '2026-11-21', 5787, NULL),
(6,  '2026-11-28', 5787, NULL),
(7,  '2026-12-05', 5787, NULL),
(8,  '2026-12-12', 5787, NULL),
(9,  '2026-12-19', 5787, NULL),
(10, '2026-12-26', 5787, NULL),
(11, '2027-01-02', 5787, NULL),
(12, '2027-01-09', 5787, NULL),
(13, '2027-01-16', 5787, NULL),
(14, '2027-01-23', 5787, NULL),
(15, '2027-01-30', 5787, NULL),
(16, '2027-02-06', 5787, NULL),
(17, '2027-02-13', 5787, NULL),
(18, '2027-02-20', 5787, NULL),
(19, '2027-02-27', 5787, NULL),
(20, '2027-03-06', 5787, NULL),
(21, '2027-03-13', 5787, NULL),
(22, '2027-03-20', 5787, NULL),
(23, '2027-03-27', 5787, NULL),
(24, '2027-04-17', 5787, NULL),
(25, '2027-04-24', 5787, NULL),
(26, '2027-05-01', 5787, NULL),
(27, '2027-05-08', 5787, NULL),
(28, '2027-05-15', 5787, NULL),
(29, '2027-05-22', 5787, NULL),
(30, '2027-05-29', 5787, NULL),
(31, '2027-06-05', 5787, NULL),
(32, '2027-06-19', 5787, NULL),
(33, '2027-06-26', 5787, NULL),
(34, '2027-07-03', 5787, NULL),
(35, '2027-07-10', 5787, NULL),
(36, '2027-07-17', 5787, NULL),
(37, '2027-07-24', 5787, NULL),
(38, '2027-07-31', 5787, NULL),
(39, '2027-08-07', 5787, NULL),
(40, '2027-08-14', 5787, NULL),
(41, '2027-08-21', 5787, NULL),
(42, '2027-08-28', 5787, 43),
(44, '2027-09-04', 5787, NULL),
(45, '2027-09-11', 5787, NULL),
(46, '2027-09-18', 5787, NULL),
(47, '2027-09-25', 5787, NULL);
